services:
    franken:
#        image: dunglas/frankenphp:latest
        build:
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal
        volumes:
            - ./app:/app/public
        ports:
            - 443:443
            - 80:80